name: Deploy Documentation

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      - 'ROADMAP.md'
      - 'LICENSE'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Fetch all history for git info

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocs-autorefs

      - name: Copy files to docs
        run: |
          cp CHANGELOG.md docs/
          cp LICENSE docs/LICENSE.md
          cp CONTRIBUTING.md docs/
          cp ROADMAP.md docs/

      - name: Build documentation
        run: mkdocs build --strict

      - name: Deploy to GitHub Pages
        # Include custom domain to preserve CNAME on each deploy
        run: mkdocs gh-deploy --force --custom-domain mnemex.dev
