name: Publish to PyPI

on:
  push:
    tags:
      - "v0.*"
      - "v0.*.*"
      - "v0.*.*.*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
      - name: Build distributions
        run: python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
